global:
  scrape_interval: 15s
  evaluation_interval: 15s

server:
  persistentVolume:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  replicas: 1
  service:
    type: NodePort
    port: 9090
    nodePort: 30090

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 1Gi  # ✅ Here’s the 1Gi you requested for Alertmanager.
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m"

pushgateway:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m"

# serverFiles:
#   prometheus.yml:
#     scrape_configs:
#       - job_name: 'kubernetes-nodes'
#         # scheme: http
#         # tls_config:
#         #   insecure_skip_verify: true
#         kubernetes_sd_configs:
#           - role: node
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_node_name]
#             target_label: node

#       - job_name: 'kubernetes-pods'
#         kubernetes_sd_configs:
#           - role: pod
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_label_app]
#             target_label: app

#       - job_name: 'kubernetes-services'
#         kubernetes_sd_configs:
#           - role: service
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_service_label_app]
#             target_label: app
