grafana:
  persistence:
    enabled: true
    size: 1Gi
  adminPassword: "1234"  

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
