global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
  - job_name: 'app'
    static_configs:
      - targets: ['app-service.observability.svc.cluster.local:3000']
