namespace: prometheus-grafana-k8s

replicaCount: 1

image:
  repository: john_duran/k8s-app # justt replace with your own repo
  tag: latest
  pullPolicy: IfNotPresent

container:
  targetPort: "3000"

service:
  port: "80"
  targetPort: "3000"

env:
  PGHOST: postgres-service
  PGUSER: postgres
  PGPASSWORD: "yourpassword"
  PGDATABASE: people
  PGPORT: "5432"