apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-credentials
  annotations:
    kubernetes.io/dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # replace with the result of aws ecr get-login-password --region us-east-1 