apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-config
  namespace: {{ .Values.namespace }}
data:
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "K8s Postgres",
                "Group": "Servers",
                "Host": "{{ .Values.pgadmin.PGHOST }}",
                "Port": 5432,
                "MaintenanceDB": "{{ .Values.pgadmin.PGDATABASE }}",
                "Username": "{{ .Values.pgadmin.PGUSER }}",
                "Password": "{{ .Values.pgadmin.PGPASSWORD }}",
                "SSLMode": "prefer"
            }
        }
    }

