apiVersion: v1
kind: Service
metadata:
  name: k8s-app
  namespace: {{ .Values.namespace }}
  labels:
    app: k8s-app
spec:
  selector:
    app: k8s-app  # The selector, it uses the service to know which pod to send the traffic to
  ports:
    - name: metrics
      protocol: TCP
      port: 80 # This is the service port (what clients use to talk to the service)
      targetPort: 3000 # This is the container port (the port inside your pod/app)
  type: NodePort
  nodePort: 32442   # Specify a NodePort in a valid range (30000-32767)