apiVersion: v1
kind: Service
metadata:
  name: k8s-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} # This is the service port (what clients use to talk to the service)
      targetPort: {{ .Values.service.targetPort }} # This is the container port (the port inside your pod/app)
  type: NodePort
