apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      imagePullSecrets:
        - name: ecr-registry-credentials
      containers:
        - name: k8s-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.container.targetPort }}
          env:
            - name: PGHOST
              value: {{ .Values.env.PGHOST }}
            - name: PGUSER
              value: {{ .Values.env.PGUSER }}
            - name: PGPASSWORD
              value: "{{ .Values.env.PGPASSWORD }}"
            - name: PGDATABASE
              value: {{ .Values.env.PGDATABASE }}
            - name: PGPORT
              value: "5432"
              
